# Generated by Django 3.1.5 on 2021-02-13 16:03

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import game.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_hash', models.CharField(default=game.models.make_hash_id, max_length=17)),
                ('current_map_hash', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('guessed_trigger', models.BooleanField()),
                ('current_guess_coordinates', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('score', models.PositiveIntegerField()),
                ('current_game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
            ],
        ),
    ]
