# Generated by Django 3.1.5 on 2021-02-15 12:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='current_guess_coordinates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), size=None),
        ),
        migrations.AlterField(
            model_name='players',
            name='guessed_trigger',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
