# Generated by Django 3.1.5 on 2021-02-24 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20210215_1300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='is_active',
            new_name='has_ended',
        ),
    ]
