version: '3.7'
#psql --host=db --username=postgres --dbname=postgres
#command: gunicorn --bind 0.0.0.0:8000 whereami.wsgi --log-level debug -> for production
#command: python manage.py runserver 0.0.0.0:8000  -> for development
#this comment is just to test the new dev branch

services:
    db:
        image: postgres
        environment: 
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
    web:
        build: ./src
        command: python manage.py runserver 0.0.0.0:8000
        volumes: 
            - ./src:/code/
        ports: 
            - 8000:8000
        env_file: 
            - .prod.env
            - .creds.env
        depends_on: 
            - db
        
