version: '3.7'

services: 
    web:
        build: ./src
        command: python manage.py runserver 0:8000
        volumes: 
            - ./src:/code/
        ports: 
            - 8000:8000
        env_file: 
            - .dev.env
        