version: '3.7'

services: 
    web:
        build: ./src/api
        command: python manage.py runserver 0:8000
        volumes: 
            - ./src/api:/code/
        ports: 
            - 8000:8000
        env_file: 
            - ./.env.dev