# Generated by Django 3.1.5 on 2021-03-01 21:41

import django.contrib.postgres.fields
from django.db import migrations, models
import map.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=map.models.make_hash_id, max_length=13)),
                ('map_type', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=50)),
                ('creator', models.CharField(max_length=40)),
                ('num_of_locations', models.IntegerField(default=0)),
                ('mapillary_image_key', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), size=None)),
                ('times_played', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ReportedImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapillary_image', models.CharField(max_length=25)),
                ('reason_is_low_quality', models.IntegerField(default=0)),
                ('reason_is_wrong_coordinates', models.IntegerField(default=0)),
            ],
        ),
    ]
