# Generated by Django 3.1.5 on 2021-03-18 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='map',
            name='name',
        ),
        migrations.RemoveField(
            model_name='map',
            name='times_played',
        ),
    ]
