# Generated by Django 3.1.5 on 2021-02-04 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_remove_map_create_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='users_who_played',
        ),
    ]
