# Generated by Django 3.1.5 on 2021-02-09 19:06

from django.db import migrations, models
import map.models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_auto_20210207_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='hash_id',
            field=models.CharField(default=map.models.make_hash_id, max_length=13),
        ),
    ]
