# Generated by Django 3.1.5 on 2021-02-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_map_hash_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='map_type',
            field=models.IntegerField(default=1),
        ),
    ]
