# Generated by Django 3.1.5 on 2021-02-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_map_map_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportedImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapillary_image', models.CharField(max_length=25)),
                ('reason_is_low_quality', models.IntegerField(default=0)),
                ('reason_is_wrong_coordinates', models.IntegerField(default=0)),
            ],
        ),
    ]
